export const DIRECTORY_TREE_TOGGLE_EXPANSION = "DIRECTORY_TREE_TOGGLE_EXPANSION";
export const DIRECTORY_CONTENT_UPDATE        = "DIRECTORY_CONTENT_UPDATE";
export const REQUEST_DIRECTORY_CONTENT       = "REQUEST_DIRECTORY_CONTENT";
